TOTAL_LIQUID_ASSETS = 20000
YEARS_OF_REINVESTMENT = 10
companies = {
    # "Lockhead Martin": "LMT",
    # "Cintas Corporation": "CTAS",
    # "Home Depot": "HD",
    # "UPS": "UPS",
    # "Target": "TGT",
    # "Texas Instruments": "TXN",
    # "Clorox": "CLX",
    "IBM": "IBM",
    # "JPMorgan Chase": "JPM",
    # "Allstate": "ALL",
    # "3M": "MMM",
    # "Exxon Mobil Corp": "XOM",
    # "Abbott Laboratories": "ABT",
    # "Philip Morris": "PM",
    # "Morgan Stanely": "MS",
    # "General Mills": "GIS",
    # "Gilead Sciences": "GILD",
    # "Kellogg": "K",
    # "Best Buy": "BBY",
    # "Tyson": "TSN",
    # "Coca-Cola Co": "KO",
    # "Pfizer": "PFE",
    # "Dow Inc": "DOW",
    # "Unilever": "UL",
    # "Cisco": "CSCO",
    # "Kraft Heniz": "KHC",
    # "Verzion": "VZ",
    # "BP": "BP",
    # "Intel": "INTC",
    # "AT&T": "T",
    # "Ford": "F"
}